// styles/realeza.js — The Royal Portrait
// V2.0 — Aesthetic upgrade: painterly oil technique, desaturated opulence, aged canvas
module.exports = function realezaStyle(gender) {
  return {
    role: [
      // ── IDENTIDAD — lo más importante ──────────────────────────────
      "IDENTITY LOCK — HIGHEST PRIORITY:",
      "Extract and transfer the exact face from the photo — same markings,",
      "fur color, eye shape, eye color, expression and head angle.",
      "Preserve the animal's natural personality exactly as it is.",
      "The owner must recognize their pet immediately.",
      "Remove any collar, leash or accessory — replace with royal costume only.",
      "",
      // ── ILUMINACIÓN ────────────────────────────────────────────────
      "LIGHTING:",
      "Single warm amber-gold light source from upper left at 45 degrees.",
      "Strong chiaroscuro — the lit side of the face is warm and bright,",
      "the shadow side drops into near-darkness. No fill light. No softboxes.",
      "One precise sharp catchlight in each eye — small, white, gives life.",
      "The gold embroidery catches light with aged warm gleam — not bright shine.",
      "Shadow areas are very deep — near black. This is not evenly lit.",
      "",
      // ── FONDO ──────────────────────────────────────────────────────
      "BACKGROUND:",
      "Deep near-black vignette consuming all four corners.",
      "Warm amber-ochre atmospheric glow concentrated behind the head only.",
      "The glow is subtle and warm — like candlelight through old varnish.",
      "Loose visible brushstrokes throughout the background — NOT a smooth gradient.",
      "Individual paint marks going in different directions — exactly like",
      "a 17th century Dutch master portrait background.",
      "No walls. No architecture. Pure atmospheric darkness with warm center glow.",
      "",
      // ── VESTIMENTA ─────────────────────────────────────────────────
      "COSTUME:",
      "White ermine mantle — individual fur hairs visible, not smooth white.",
      "Small evenly-distributed black spots on the ermine — classic royal pattern.",
      "Drapes from behind the shoulders, ermine border frames the chest naturally.",
      "Gold embroidery with floral motifs along the ermine border —",
      "aged gold thread, not bright yellow. Warm tarnished gleam.",
      "Deep burgundy-wine velvet cape — very dark, almost wine-black.",
      "NOT bright red. NOT crimson. The velvet absorbs light — matte and heavy.",
      "Sits behind the animal at shoulder level, visible on both sides.",
      "NEVER in front. NEVER covering the face or chest.",
      "Deep dramatic fold shadows carved into the velvet — real physical weight.",
      "Ornate double gold chain at chest — aged gold, warm tone, not shiny.",
      "Large gemstone medallion pendant — deep emerald or sapphire, catches light.",
      "",
      // ── COJÍN ──────────────────────────────────────────────────────
      "CUSHION:",
      "Large heavily-stuffed deep burgundy velvet cushion — almost square.",
      "The same dark wine-burgundy as the cape — unified palette.",
      "Directional velvet sheen — bright highlight on the top surface,",
      "deep shadow falling on front face and sides.",
      "Aged gold fringe trim along all edges — individual fringe strands visible.",
      "One large ornate gold tassel at front center.",
      "Stone ledge clearly visible below — plain flat grey, no decoration.",
      "",
      // ── TÉCNICA PICTÓRICA ──────────────────────────────────────────
      "PAINTING TECHNIQUE:",
      "This is a physical oil painting on canvas. Not a digital render.",
      "Do NOT render this digitally. Do NOT use smooth AI gradients anywhere.",
      "FUR: dark undertone base layer first.",
      "Individual lighter fur strands painted on top with short directional",
      "brushstrokes following the natural direction of hair growth.",
      "Fur has depth — shadow underneath, individual hairs catching light on top.",
      "VELVET: painted with long directional strokes. Nap direction visible.",
      "BACKGROUND: loose expressive brushwork — strokes visible and intentional.",
      "Fine craquelure throughout — most visible in dark areas and deep shadows.",
      "Canvas weave texture visible under the paint in all areas.",
      "Muted desaturated palette throughout — no vivid digital colors.",
      "All reds are deep burgundy-wine. All golds are aged warm ochre.",
      "The entire painting looks like it was executed in the 17th century",
      "and has hung in a museum for 300 years.",
    ].join("\n")
  };
};
